language: node_js
node_js:
  - "10"
env:
  - MOZ_HEADLESS=1
addons:
  chrome: stable
  firefox: latest
before_install:
  - "google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &"
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "sleep 3"
  - "sudo chown root /opt/google/chrome/chrome-sandbox"
  - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
script: "npm run lint && npm test"
notifications:
  email: false
