query: '
mutation updateIssue($issueId: ID!, $projectId: ID!) {
  updateIssue(input: { id: $issueId, projectIds: [$projectId] }) {
    issue {
      id
    }
  }
}'
variables:
  issueId:
    type: jq
    file: ../workflow/event.json
    query: '.issue.node_id'
  projectId: "MDc6UHJvamVjdDI0ODA4MDQ="
