name: CI

on:
  - push:
    branches:
      - master
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Test
        run: echo 'test test'
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo 'hello world'
