name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      env:
        CI: true
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm i
      - run: npm test
  build:
    needs: test
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo 'hello world'
